### ISSUE TITLE
[Bug] Common Language Runtime detected an invalid program. Exception

### ISSUE THREAD

**Issue by Tesagi** [UnrealSharp/UnrealSharp#264]
After last update with Getters and Setters if u try add some value to TArray or TMap (maybe in another types too)

```
System.InvalidProgramException: Common Language Runtime detected an invalid program.
```

StackTrace:
```
   at Core.Test.UTestInventoryComponent.get_Items()
   at Core.Test.UTestInventoryComponent.BeginPlay_Implementation() in F:\GIT\RPGSharp\Script\Core\Test\UTestInventoryComponent.cs:line 23
   at UnrealSharp.Engine.UActorComponent.Invoke_ReceiveBeginPlay(IntPtr buffer, IntPtr returnBuffer) in F:\GIT\RPGSharp\Plugins\UnrealSharp\Managed\UnrealSharp\UnrealSharp\Generated\Engine\ActorComponent.generated.cs:line 1213
   at UnrealSharp.Interop.UnmanagedCallbacks.InvokeManagedMethod(IntPtr managedObjectHandle,  methodPtr, IntPtr argumentsBuffer, IntPtr returnValueBuffer, IntPtr exceptionTextBuffer) in F:\GIT\RPGSharp\Plugins\UnrealSharp\Managed\UnrealSharp\UnrealSharp\Interop\UnmanagedCallbacks.cs:line 167
```

![image](https://github.com/user-attachments/assets/4cebd3d5-acdb-4195-ba66-5d31d8b20a2b)

![image](https://github.com/user-attachments/assets/b46cba4b-1790-4cf2-9214-e173f11e3de8)

**Comment by Tesagi** [comment]
After clean install problem gone =/
