### ISSUE TITLE
Spawning a character or accessing a component in C# causes a crash.

### ISSUE THREAD

**Issue by redasm** [UnrealSharp/UnrealSharp#281]
![image](https://github.com/user-attachments/assets/40d39db1-4a7e-4413-99f3-67ec845925ce)
![image](https://github.com/user-attachments/assets/d3f6fdd1-545f-4643-b052-0773e85532d1)

Fatal error detected: "System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
   at System.Reflection.RuntimeModule.GetTypes(QCallModule module, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeModule.GetDefinedTypes()
   at System.Reflection.RuntimeModule.GetTypes()
   at UnrealSharp.Interop.UnmanagedCallbacks.FindTypeInAssembly(Assembly assembly, String fullTypeName) in F:\UEProject\CaroGame\EcsDemo\Plugins\UnrealSharp\Managed\UnrealSharp\UnrealSharp\Interop\UnmanagedCallbacks.cs:line 125
   at UnrealSharp.Interop.UnmanagedCallbacks.LookupManagedType(IntPtr assemblyHandle, Char* typeNamespace, Char* typeEngineName) in F:\UEProject\CaroGame\EcsDemo\Plugins\UnrealSharp\Managed\UnrealSharp\UnrealSharp\Interop\UnmanagedCallbacks.cs:line 97
   at UnrealSharp.Interop.FCSManagerExporter.CallFindManagedObject(IntPtr a) in F:\UEProject\CaroGame\EcsDemo\Plugins\UnrealSharp\Managed\UnrealSharp\UnrealSharp\obj\Debug\net9.0\UnrealSharp.SourceGenerators\UnrealSharp.SourceGenerators.NativeCallbacksWrapperGenerator\FCSManagerExporter.generated.cs:line 16
   at UnrealSharp.ObjectMarshaller`1.FromNative(IntPtr nativeBuffer, Int32 arrayIndex) in F:\UEProject\CaroGame\EcsDemo\Plugins\UnrealSharp\Managed\UnrealSharp\UnrealSharp\Marshallers.cs:line 101
   at UnrealSharp.EcsDemo.ACharacterBase.get_ActorDataComp() in F:\UEProject\CaroGame\EcsDemo\Script\ProjectGlue\EcsDemo\CharacterBase.generated.cs:line 26
   at Game.Character.APlayerCharacter.ReceivePostInitializeComponents_Implementation() in F:\UEProject\CaroGame\EcsDemo\Script\Game\Character\PlayerCharacter.cs:line 17
   at UnrealSharp.EcsDemo.ACharacterBase.Invoke_ReceivePostInitializeComponents(IntPtr buffer, IntPtr returnBuffer) in F:\UEProject\CaroGame\EcsDemo\Script\ProjectGlue\EcsDemo\CharacterBase.generated.cs:line 55
   at UnrealSharp.Interop.UnmanagedCallbacks.InvokeManagedMethod(IntPtr managedObjectHandle,  methodPtr, IntPtr argumentsBuffer, IntPtr returnValueBuffer, IntPtr exceptionTextBuffer) in F:\UEProject\CaroGame\EcsDemo\Plugins\UnrealSharp\Managed\UnrealSharp\UnrealSharp\Interop\UnmanagedCallbacks.cs:line 167
System.IO.FileLoadException: Could not load file or assembly 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
   at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at UnrealSharp.Plugins.PluginLoadContext.Load(AssemblyName assemblyName) in F:\UEProject\CaroGame\EcsDemo\Plugins\UnrealSharp\Managed\UnrealSharp\UnrealSharp.Plugins\PluginLoader.cs:line 72
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
System.IO.FileLoadException: Could not load file or assembly 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
   at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at UnrealSharp.Plugins.PluginLoadContext.Load(AssemblyName assemblyName) in F:\UEProject\CaroGame\EcsDemo\Plugins\UnrealSharp\Managed\UnrealSharp\UnrealSharp.Plugins\PluginLoader.cs:line 72
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
System.IO.FileLoadException: Could not load file or assembly 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
   at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at UnrealSharp.Plugins.PluginLoadContext.Load(AssemblyName assemblyName) in F:\UEProject\CaroGame\EcsDemo\Plugins\UnrealSharp\Managed\UnrealSharp\UnrealSharp.Plugins\PluginLoader.cs:line 72
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
System.IO.FileLoadException: Could not load file or assembly 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
   at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at UnrealSharp.Plugins.PluginLoadContext.Load(AssemblyName assemblyName) in F:\UEProject\CaroGame\EcsDemo\Plugins\UnrealSharp\Managed\UnrealSharp\UnrealSharp.Plugins\PluginLoader.cs:line 72
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
System.IO.FileLoadException: Could not load file or assembly 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
   at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at UnrealSharp.Plugins.PluginLoadContext.Load(AssemblyName assemblyName) in F:\UEProject\CaroGame\EcsDemo\Plugins\UnrealSharp\Managed\UnrealSharp\UnrealSharp.Plugins\PluginLoader.cs:line 72
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
System.IO.FileLoadException: Could not load file or assembly 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
   at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at UnrealSharp.Plugins.PluginLoadContext.Load(AssemblyName assemblyName) in F:\UEProject\CaroGame\EcsDemo\Plugins\UnrealSharp\Managed\UnrealSharp\UnrealSharp.Plugins\PluginLoader.cs:line 72
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
System.IO.FileLoadException: Could not load file or assembly 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
   at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at UnrealSharp.Plugins.PluginLoadContext.Load(AssemblyName assemblyName) in F:\UEProject\CaroGame\EcsDemo\Plugins\UnrealSharp\Managed\UnrealSharp\UnrealSharp.Plugins\PluginLoader.cs:line 72
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
System.IO.FileLoadException: Could not load file or assembly 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
   at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at UnrealSharp.Plugins.PluginLoadContext.Load(AssemblyName assemblyName) in F:\UEProject\CaroGame\EcsDemo\Plugins\UnrealSharp\Managed\UnrealSharp\UnrealSharp.Plugins\PluginLoader.cs:line 72
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
System.IO.FileLoadException: Could not load file or assembly 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
   at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at UnrealSharp.Plugins.PluginLoadContext.Load(AssemblyName assemblyName) in F:\UEProject\CaroGame\EcsDemo\Plugins\UnrealSharp\Managed\UnrealSharp\UnrealSharp.Plugins\PluginLoader.cs:line 72
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)". Blueprint:  PlayerCharacter Function:  Receive Post Initialize Components Call Stack:  Show

**Comment by OlssonDev** [comment]
https://github.com/UnrealSharp/UnrealSharp/commit/b6b708ae2ca42778628e111e3f970d9c8718b3f0

Try now!
