### ISSUE TITLE
 Type "UnrealSharp.Vector2DMarshaller" not found in userAssembly UnrealSharp

### ISSUE THREAD

**Issue by jcoder58** [UnrealSharp/UnrealSharp#53]
Defined this function

```C#
    [UFunction(FunctionFlags.BlueprintCallable)]
    protected void Look(Vector2D axis)
    {

    }
```

and get this error when starting the editor:

    UnrealSharpBuildTool task failed: 
     An error occurred: Error in executing build command : 
    Error during assembly processing: Type "UnrealSharp.Vector2DMarshaller" not found in userAssembly UnrealSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
    Exception processing C:\UnrealEngine\UnrealSharp\TestUnrealSharp\Script\bin\Debug\net8.0\ManagedTestUnrealSharp.dll: Type "UnrealSharp.Vector2DMarshaller" not found in userAssembly UnrealSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
       at UnrealSharpWeaver.WeaverHelper.FindTypeInAssembly(AssemblyDefinition assembly, String typeNamespace, String typeName, Boolean throwOnException) in C:\UnrealEngine\UnrealSharp\TestUnrealSharp\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\WeaverHelper.cs:line 96
       at UnrealSharpWeaver.NativeTypes.NativeDataSimpleType.PrepareForRewrite(TypeDefinition typeDefinition, FunctionMetaData functionMetadata, PropertyMetaData propertyMetadata) in C:\UnrealEngine\UnrealSharp\TestUnrealSharp\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\NativeTypes\NativeDataSimpleType.cs:line 51
       at UnrealSharpWeaver.Rewriters.FunctionRewriterHelpers.MakeManagedMethodInvoker(TypeDefinition type, FunctionMetaData func, MethodDefinition methodToCall, List`1 paramOffsetFields) in C:\UnrealEngine\UnrealSharp\TestUnrealSharp\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\Rewriters\FunctionRewriterHelpers.cs:line 166
       at UnrealSharpWeaver.Rewriters.FunctionRewriterHelpers.ProcessMethods(List`1 functionsToRewrite, ClassMetaData classMetaData, TypeDefinition classDefinition, Dictionary`2& functionPointersToInitialize, List`1& functionParamSizesToInitialize, List`1& functionParamOffsetsToInitialize, List`1& functionParamElementSizesToInitialize) in C:\UnrealEngine\UnrealSharp\TestUnrealSharp\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\Rewriters\FunctionRewriterHelpers.cs:line 78
       at UnrealSharpWeaver.Rewriters.UnrealClassProcessor.ProcessClass(TypeDefinition classTypeDefinition, ClassMetaData metadata) in C:\UnrealEngine\UnrealSharp\TestUnrealSharp\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\Rewriters\UnrealClassProcessor.cs:line 52
       at UnrealSharpWeaver.Rewriters.UnrealClassProcessor.ProcessParentClass(TypeDefinition type, IReadOnlyDictionary`2 classDictionary, HashSet`1& rewrittenClasses) in C:\UnrealEngine\UnrealSharp\TestUnrealSharp\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\Rewriters\UnrealClassProcessor.cs:line 35
       at UnrealSharpWeaver.Rewriters.UnrealClassProcessor.ProcessClasses(IEnumerable`1 classes, ApiMetaData assemblyMetadata) in C:\UnrealEngine\UnrealSharp\TestUnrealSharp\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\Rewriters\UnrealClassProcessor.cs:line 17
       at UnrealSharpWeaver.Program.StartProcessingAssembly(AssemblyDefinition userAssembly, ApiMetaData metadata) in C:\UnrealEngine\UnrealSharp\TestUnrealSharp\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\Program.cs:line 211
       at UnrealSharpWeaver.Program.StartWeavingAssembly(AssemblyDefinition assembly, String assemblyOutputPath, BaseAssemblyResolver resolver) in C:\UnrealEngine\UnrealSharp\TestUnrealSharp\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\Program.cs:line 137
       at UnrealSharpWeaver.Program.LoadUserAssembly(WeaverOptions weaverOptions, DefaultAssemblyResolver resolver) in C:\UnrealEngine\UnrealSharp\TestUnrealSharp\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\Program.cs:line 111

**Comment by OlssonDev** [comment]
It's Vector2
