### ISSUE TITLE
Runtime errors are hidden when not running the project in Debug mode

### ISSUE THREAD

**Issue by cronofear-dev** [UnrealSharp/UnrealSharp#67]
This can be replicated by having an Actor instance calling `ExampleFunction` (and not have any tag in such Actor) from:
```csharp
[UClass]
public class ExampleActor2 : Actor
{
    protected ExampleActor2(IntPtr nativeObject) : base(nativeObject)
    {
    }
    
    [UFunction(FunctionFlags.BlueprintCallable)]
    public void ExampleFunction()
    {
        // This should throw an error if the Actor doesn't have any tag
        var tag = Tags[0];
        PrintString($"First tag is {tag}");
    }
}
```

When a project is opened manually (by opening the .uproject file), then there's no indication that there's an error anywhere. The BP will just skip any call to `ExampleFunction`.

When a project is opened from the ManagedProject.sln file in Rider (Run/Debug), then the error will be logged in the Run/Debug window and there will be an indication of an error only when running in debug mode (exception throw).

```
Exception during InvokeManagedMethod: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IndexOutOfRangeException: Index 0 is out of bounds. Array size is 0.
   at UnrealSharp.UnrealArrayReadWrite`1.get_Item(Int32 index) in ..\Plugins\UnrealSharp\Managed\UnrealSharp\UnrealSharp\UnrealArray.cs:line 179
   at ManagedProject.Examples.ExampleActor2.ExampleFunction() in ..\Script\Examples\Example_Functions.cs:line 130
   at ManagedProject.Examples.ExampleActor2.Invoke_ExampleFunction(IntPtr, IntPtr)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at UnrealSharp.Interop.UnmanagedCallbacks.InvokeManagedMethod(IntPtr managedObjectPtr, IntPtr methodHandlePtr, IntPtr argumentsBuffer, IntPtr returnValueBuffer) in ..\Plugins\UnrealSharp\Managed\UnrealSharp\UnrealSharp\Interop\UnmanagedCallbacks.cs:line 140
```

**Comment by thomasfn** [comment]
This might be addressed by https://github.com/UnrealSharp/UnrealSharp/pull/87, although I'm not sure what exactly happens in a standalone/release build.
