### ISSUE TITLE
Error when attempting to expose FIntPoint to BP, also happens with FTransform

### ISSUE THREAD

**Issue by cronofear-dev** [UnrealSharp/UnrealSharp#68]
I get an error when I try to expose IntPoint to BP. It looks like an edge case by looking at how FIntPoint is defined in cpp.

```csharp
[UClass]
public class CSMapGenerator : Actor
{
    protected CSMapGenerator(IntPtr nativeObject) : base(nativeObject)
    {
    }

    [UProperty(PropertyFlags.BlueprintReadWrite | PropertyFlags.EditAnywhere)]
    public IntPoint MyTestPoint { get; set; }
}
```

```bat
UnrealSharpBuildTool task failed: 
 An error occurred: Error in executing build command : 
Error during assembly processing: Type "UnrealSharp.CoreUObject.IntPointMarshaller" not found in userAssembly ManagedMyProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Exception processing C:\WS\MyProject\Script\bin\Debug\net8.0\ManagedMyProject.dll: Type "UnrealSharp.CoreUObject.IntPointMarshaller" not found in userAssembly ManagedMyProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
   at UnrealSharpWeaver.WeaverHelper.FindTypeInAssembly(AssemblyDefinition assembly, String typeNamespace, String typeName, Boolean throwOnException) in C:\WS\MyProject\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\WeaverHelper.cs:line 101
   at UnrealSharpWeaver.NativeTypes.NativeDataSimpleType.PrepareForRewrite(TypeDefinition typeDefinition, FunctionMetaData functionMetadata, PropertyMetaData propertyMetadata) in C:\WS\MyProject\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\NativeTypes\NativeDataSimpleType.cs:line 50
   at UnrealSharpWeaver.Rewriters.PropertyRewriterHelpers.ProcessProperties(List`1& propertyOffsetsToInitialize, List`1& propertyPointersToInitialize, TypeDefinition type, IEnumerable`1 properties) in C:\WS\MyProject\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\Rewriters\PropertyRewriterHelpers.cs:line 34
   at UnrealSharpWeaver.Rewriters.UnrealClassProcessor.ProcessClass(TypeDefinition classTypeDefinition, ClassMetaData metadata) in C:\WS\MyProject\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\Rewriters\UnrealClassProcessor.cs:line 44
   at UnrealSharpWeaver.Rewriters.UnrealClassProcessor.ProcessParentClass(TypeDefinition type, IReadOnlyDictionary`2 classDictionary, HashSet`1& rewrittenClasses) in C:\WS\MyProject\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\Rewriters\UnrealClassProcessor.cs:line 35
   at UnrealSharpWeaver.Rewriters.UnrealClassProcessor.ProcessClasses(IEnumerable`1 classes, ApiMetaData assemblyMetadata) in C:\WS\MyProject\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\Rewriters\UnrealClassProcessor.cs:line 17
   at UnrealSharpWeaver.Program.StartProcessingAssembly(AssemblyDefinition userAssembly, ApiMetaData metadata) in C:\WS\MyProject\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\Program.cs:line 219
   at UnrealSharpWeaver.Program.StartWeavingAssembly(AssemblyDefinition assembly, String assemblyOutputPath, BaseAssemblyResolver resolver) in C:\WS\MyProject\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\Program.cs:line 138
   at UnrealSharpWeaver.Program.LoadUserAssembly(WeaverOptions weaverOptions, DefaultAssemblyResolver resolver) in C:\WS\MyProject\Plugins\UnrealSharp\Managed\UnrealSharpPrograms\UnrealSharpWeaver\Program.cs:line 112
```

**Comment by cronofear-dev** [comment]
This issue seems to also happen with FTransform.
